/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.10.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("com.diffplug.spotless") version "6.21.0"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()

    maven {
          url = uri("https://repo.itextsupport.com/android")
    }
}


dependencies {
    // Use JUnit test framework.
    testImplementation(libs.junit)

    // This dependency is used by the application.
    implementation(libs.guava)

    implementation("com.itextpdf.android:kernel-android:7.2.5")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

spotless {
    java {
        target("src/**/*.java") // Apply to all Kotlin files in the src directory
        googleJavaFormat()    // Use Google's Java format style
        trimTrailingWhitespace() // Remove trailing whitespace
        endWithNewline()      // Ensure files end with a newline
        removeUnusedImports() // Remove unused imports
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.example.App"
}
